- name: Install RabbitMQ
  hosts: rmqsrvgrp
  become: yes

  tasks:
    - name: Install Erlang
      apt:
        name: erlang
        state: present
      when: ansible_distribution == 'Ubuntu'  # Adjust for other OS distributions

    - name: Install RabbitMQ package
      package:
        name: rabbitmq-server
        state: present
      when: ansible_distribution == 'Ubuntu'  # Adjust for other OS distributions

    - name: Enable and start RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
    - name: config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
         - Restart RMQ
      tags:
        - conf
    - rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf
    - name: Enables the rabbitmq-management plugin
      rabbitmq_plugin:
         names: rabbitmq_management
         state: enabled
      notify:
        - Restart RMQ
      tags:
        - package
  handlers:
    - name: Restart RMQ
      service:
         name: rabbitmq-server
         state: restarted
