---
- name: Install RabbitMQ on Ubuntu 18.04
  hosts: rmqsrvgrp
  become: yes

  tasks:
    - name: Add RabbitMQ APT repository
      apt_repository:
        repo: "deb https://dl.bintray.com/rabbitmq/debian bionic main"
        state: present
        filename: "bintray.rabbitmq.list"
        update_cache: yes

    - name: Import RabbitMQ signing key
      apt_key:
        url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
        state: present

    - name: Install RabbitMQ package
      apt:
        name: rabbitmq-server
        state: present


    - name: Config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ
      tags:
        - conf


    - rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf


    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted