---
- name: Install & setup RabbitMQ with user
  hosts: rmqsrvgrp
  tasks:
    - name: Install Erlang Repository package
      apt:
        deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    - name: Add an Erlang solution public key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present
    - name: Install Erlang
      apt:
       name: erlang
       update_cache: yes
       state: present
    - name: primary RabbitMQ signing key
      shell: 'curl -1sLf "https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.github.rabbitmq.signing.gpg > /dev/null'
    - name: Launchpad PPA signing key for apt
      shell: 'curl -1sLf "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf77f1eda57ebb1cc" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg > /dev/null'
    - name: updating
      shell: 'apt-get update'
    - name: installing RabbitMq-server
      apt:
       name: rabbitmq-server
       state: present
       update_cache: yes
    - name: Restarts and enables RMQ
      service:
         name: rabbitmq-server
         state: started
         enabled: yes
    - name: config setup
      copy:
       content: |
        [{rabbit, [{loopback_users, []}]}].
       dest: /etc/rabbitmq/rabbitmq.config

    - rabbitmq_user:
         user: test
         password: test
         configure_priv: .*
         read_priv: .*
         write_priv: .*
         tags: administrator
         state: present

    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin:
         names: rabbitmq_management
         state: enabled

    - name: restart rmq
      service:
         name: rabbitmq-server
         state: restarted